clc
clear
r1 = randi([-30, 30], 7, 1)
r2 = randi([-30, 30], 1, 7)

x = randi([-30, 0], 1, 1):randi([1, 5], 1, 1):randi([5, 30], 1, 1)

d = randi([-30, 30], 7, 7)
b = magic(7)

d1 = d([4:6], [1:3])
d2 = d;
d2(:, 4) = [0]
d3 = d([1 3 4 5 6 7], :)
d4 = d([3 2 1 4 5 6 7], :)

disp('d + b:')
disp(d + b)
disp('d * b: ')
disp(d * b)
disp('d .* b: ')
disp(d .* b)
disp('r2 * d: ')
disp(r2 * d)
disp('d ./ b: ')
disp(d ./ b)
disp('(округл.) d ./ b: ')
disp(round(d ./ b))
disp('b^2: ')
disp(b^2)
disp('b.^2: ')
disp(b.^2)

disp('d^(-1): ')
disp(inv(d))
disp('Трансп. матр. d: ')
disp(d')
disp('След матр. d: ')
disp(trace(d))
disp('Сумма матр. d по столбцам: ')
disp(sum(d))
disp('Сумма матр. d по строкам: ')
disp(sum(d, 2))
disp('Сумма всех элем. матр. d: ')
disp(sum(sum(d)))
disp('Произв. всех элем. матр. d: ')
disp(prod(prod(d)))
disp('Произв. элем. матр. d в столбцах: ')
disp(prod(d))
disp('Произв. элем. матр. d в строках: ')
disp(prod(d, 2))
disp('Наим. элем. матр. d по столбцам: ')
disp(min(d, [], 1))
disp('Наиб. элем. матр. d по столбцам: ')
disp(max(d, [], 1))
disp('Наим. элем. матр. d по строкам: ')
disp(min(d, [], 2))
disp('Наиб. элем. матр. d по строкам: ')
disp(max(d, [], 2))
disp('Длина вектора r2: ')
disp(length(r2))
disp('Наим. элем. вектора r1: ')
disp(min(r2))
disp('Наиб. элем. вектора r1: ')
disp(max(r2))
disp('Главная диаг. матр. d: ')
disp(diag(d))
disp('Побочная диаг. матр. d: ')
disp(diag(fliplr(d)))